jobs:
  include:
    - stage: build image
      services:
        - docker
      script:
        - ./build_image.sh bombergame/gateway
      after_success:
        - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
            ./push_image.sh bombergame/gateway;
          fi

    - stage: deploy
      services:
        - docker
      script:
        - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
            ./deploy.sh;
          fi
